rule all:
    input:
        "../ProcessedData/E3List.txt",
        "../ProcessedData/targetProteinList.txt"

rule format_E3_Substrate_file:
    input:
        "../Data/OriginalE3Substrate.txt"
    output:
        "../Data/E3Substrate.txt"
    script:
        "FixE3SubstrateEntry.py"

rule get_E3_list:
    input:
        "../Data/E3Substrate.txt"
    output:
        "../ProcessedData/E3List.txt"
    script:
        "E3List.R"

rule get_target_protein_list:
    input:
        "../Data/E3Substrate.txt"
    output:
        "../ProcessedData/targetProteinList.txt"
    script:
        "targetProteinList.R"

